package ciclo.de.desenvolvimento;

import javax.swing.JOptionPane;

public class Menu_Juridico extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Juridico
     */
    public Menu_Juridico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Campor_Bairro = new javax.swing.JTextField();
        Campo_Nome = new javax.swing.JTextField();
        Campo_CNPJ = new javax.swing.JTextField();
        Campo_Cidade = new javax.swing.JTextField();
        Campo_Tipo = new javax.swing.JTextField();
        Campo_Endereco = new javax.swing.JTextField();
        Campo_CEP = new javax.swing.JTextField();
        Campo_Estado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Campo_Email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Campo_DDD = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Campo_Telefone = new javax.swing.JTextField();
        Botao_Entrada = new javax.swing.JButton();
        Botao_Voltar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Campor_Bairro.setBackground(new java.awt.Color(51, 51, 51));
        Campor_Bairro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campor_Bairro.setForeground(new java.awt.Color(255, 204, 0));
        Campor_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campor_BairroActionPerformed(evt);
            }
        });
        jPanel1.add(Campor_Bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 100, -1));

        Campo_Nome.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Nome.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Nome.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_NomeActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, -1));

        Campo_CNPJ.setBackground(new java.awt.Color(51, 51, 51));
        Campo_CNPJ.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_CNPJ.setForeground(new java.awt.Color(255, 204, 0));
        Campo_CNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_CNPJActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_CNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 100, -1));

        Campo_Cidade.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Cidade.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Cidade.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_CidadeActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 100, -1));

        Campo_Tipo.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Tipo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Tipo.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_TipoActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 100, -1));

        Campo_Endereco.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Endereco.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Endereco.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_EnderecoActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        Campo_CEP.setBackground(new java.awt.Color(51, 51, 51));
        Campo_CEP.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_CEP.setForeground(new java.awt.Color(255, 204, 0));
        Campo_CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_CEPActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_CEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 100, -1));

        Campo_Estado.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Estado.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Estado.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_EstadoActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome da Empresa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CNPJ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bairro");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cidade");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CEP");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informações Pessoais");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 31));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Localização");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 155, 37));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contato");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 292, 90, 29));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        Campo_Email.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Email.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Email.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 100, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DDD");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        Campo_DDD.setBackground(new java.awt.Color(51, 51, 51));
        Campo_DDD.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_DDD.setForeground(new java.awt.Color(255, 204, 0));
        Campo_DDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_DDDActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_DDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 40, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Telefone");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        Campo_Telefone.setBackground(new java.awt.Color(51, 51, 51));
        Campo_Telefone.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Campo_Telefone.setForeground(new java.awt.Color(255, 204, 0));
        Campo_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_TelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(Campo_Telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 100, -1));

        Botao_Entrada.setBackground(new java.awt.Color(51, 51, 51));
        Botao_Entrada.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Botao_Entrada.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Entrada.setText("Entrar");
        Botao_Entrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Botao_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_EntradaActionPerformed(evt);
            }
        });
        jPanel1.add(Botao_Entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 100, 50));

        Botao_Voltar.setBackground(new java.awt.Color(51, 51, 51));
        Botao_Voltar.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Botao_Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Botao_Voltar.setText("Voltar");
        Botao_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botao_VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Botao_Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 110, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ciclo/de/desenvolvimento/Wayne_Logo_W.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 440, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Campo_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_NomeActionPerformed
        Empresa nome = new Empresa();
        nome.getNome();
    }//GEN-LAST:event_Campo_NomeActionPerformed

    private void Campo_CNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_CNPJActionPerformed
        Empresa cnpj = new Empresa();
        cnpj.getCnpj();
    }//GEN-LAST:event_Campo_CNPJActionPerformed

    private void Campo_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_TipoActionPerformed
        Empresa tipo = new Empresa();
        tipo.getTipo();
    }//GEN-LAST:event_Campo_TipoActionPerformed
    
    private void Campo_CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_CEPActionPerformed
        Empresa cep = new Empresa();
        cep.getCep();
    }//GEN-LAST:event_Campo_CEPActionPerformed

    private void Campo_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_CidadeActionPerformed
        Empresa cidade = new Empresa();
        cidade.getCidade();
    }//GEN-LAST:event_Campo_CidadeActionPerformed

    private void Campo_EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_EstadoActionPerformed
        Empresa estado = new Empresa();
        estado.getEstado();
    }//GEN-LAST:event_Campo_EstadoActionPerformed

    private void Campo_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_EmailActionPerformed
        Empresa email = new Empresa();
        email.getEmail();
    }//GEN-LAST:event_Campo_EmailActionPerformed

    private void Campo_DDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_DDDActionPerformed
        Empresa ddd = new Empresa();
        ddd.getDdd();

    }//GEN-LAST:event_Campo_DDDActionPerformed

    private void Campo_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_TelefoneActionPerformed
        Empresa telefone = new Empresa();
        telefone.getTelefone();
    }//GEN-LAST:event_Campo_TelefoneActionPerformed
    
    private void Botao_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_EntradaActionPerformed
        Empresa nome = new Empresa();
        nome.setNome(Campo_Nome.getText());
        
        Empresa cnpj = new Empresa();       
        cnpj.setCnpj(Integer.parseInt(Campo_CNPJ.getText()));
        
        
        Empresa tipo = new Empresa();
        tipo.setTipo(Campo_Tipo.getText());
        
        Empresa endereco = new Empresa();
        endereco.setEndereco(Campo_Endereco.getText());
        
        Empresa bairro = new Empresa();
        bairro.setBairro(Campor_Bairro.getText());
        
        Empresa cep = new Empresa();
        cep.setCep(Campo_CEP.getText());
        
        Empresa cidade = new Empresa();
        cidade.setCidade(Campo_Cidade.getText());
        
        Empresa estado = new Empresa();
        estado.setEstado(Campo_Estado.getText());

        Empresa email = new Empresa();
        email.setEmail(Campo_Email.getText());
        
        Empresa ddd = new Empresa();
        ddd.setDdd(Integer.parseInt(Campo_DDD.getText()));
        
        Empresa telefone = new Empresa();
        telefone.setTelefone(Integer.parseInt(Campo_Telefone.getText()));
                
        if(!"Wayne Tech".equals(nome.getNome()) && !"WayneTech".equals(nome.getNome()) &&
           !"wayne tech".equals(nome.getNome()) && !"waynetech".equals(nome.getNome())){
            
            JOptionPane.showMessageDialog(null, "Nome da Empresa Inválido");
            
        }else if(!"213243".equals(String.valueOf(cnpj.getCnpj()))){
            
            JOptionPane.showMessageDialog(null, "CNPJ Inválido");
        }else if(!"Privado".equals(tipo.getTipo()) && !"privado".equals(tipo.getTipo()) && 
                 !"Publico".equals(tipo.getTipo()) && !"Privado".equals(tipo.getTipo())){
            
            JOptionPane.showMessageDialog(null, "Tipo Inválido");
            
        }else if(!"Rua Batman o Cavaleiro das Trevas número 2172".equals(endereco.getEndereco()) &&
                 !"rua batman o cavaleiro das trevas numero 2172".equals(endereco.getEndereco()) && 
                 !"rua batman o cavaleiro das trevas número 2172".equals(endereco.getEndereco()) && 
                 !"RuaBatmanoCavaleirodasTrevasnúmero2172".equals(endereco.getEndereco()) &&
                 !"RuaBatmanoCavaleirodasTrevasnumero2172".equals(endereco.getEndereco()) && 
                 !"ruabatmanocavaleirodastrevasnúmero2172".equals(endereco.getEndereco()) && 
                 !"ruabatmanocavaleirodastrevasnumero2172".equals(endereco.getEndereco())){
            
            JOptionPane.showMessageDialog(null, "Endereço Inválido");
            
        }else if(!"Gotham Village".equals(bairro.getBairro()) && 
                 !"gotham village".equals(bairro.getBairro()) && 
                 !"Gotham village".equals(bairro.getBairro()) && 
                 !"gotham Village".equals(bairro.getBairro()) &&
                 !"GothamVillage".equals(bairro.getBairro()) && 
                 !"gothamvillage".equals(bairro.getBairro()) && 
                 !"Gothamvillage".equals(bairro.getBairro()) && 
                 !"gothamvillage".equals(bairro.getBairro())){
            
            JOptionPane.showMessageDialog(null, "Bairro Inválido");
            
        }else if(!"2172".equals(cep.getCep())){
            
            JOptionPane.showMessageDialog(null, "CEP Inválido");
            
        }else if(!"Gotham City".equals(cidade.getCidade()) && !"GothamCity".equals(cidade.getCidade()) && 
                 !"gotham city".equals(cidade.getCidade()) && !"gotham City".equals(cidade.getCidade()) &&
                 !"Gotham city".equals(cidade.getCidade()) && !"gothamcity".equals(cidade.getCidade()) && 
                 !"gothamCity".equals(cidade.getCidade()) && !"Gothamcity".equals(cidade.getCidade())){
            
            JOptionPane.showMessageDialog(null, "Cidade Inválido");
            
        }else if(!"New Jersey".equals(estado.getEstado()) && !"New jersey".equals(estado.getEstado()) && 
                 !"new Jersey".equals(estado.getEstado()) && !"new jersey".equals(estado.getEstado()) &&
                 !"NewJersey".equals(estado.getEstado()) && !"Newjersey".equals(estado.getEstado()) &&
                 !"newJersey".equals(estado.getEstado()) && !"newjersey".equals(estado.getEstado())){
            
            JOptionPane.showMessageDialog(null, "Estado Inválido");
            
        }else if(!"waynetech@gmail.com".equals(email.getEmail())){
            
            JOptionPane.showMessageDialog(null, "Email Inválido");
            
        }else if(!"21".equals(String.valueOf(ddd.getDdd()))){
            
            JOptionPane.showMessageDialog(null, "DDD Inválido");
            
        }else if(!"908978".equals(String.valueOf(telefone.getTelefone()))){
            
            JOptionPane.showMessageDialog(null, "Telefone Inválido");
            
        }else{
            JOptionPane.showMessageDialog(null, "Bem Vindo a Wayne Tech");
            dispose();
        }

    }//GEN-LAST:event_Botao_EntradaActionPerformed

    private void Campo_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_EnderecoActionPerformed
        Empresa endereco = new Empresa();
        endereco.getEndereco();
    }//GEN-LAST:event_Campo_EnderecoActionPerformed

    private void Campor_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campor_BairroActionPerformed
        Empresa bairro = new Empresa();
        bairro.getBairro();
    }//GEN-LAST:event_Campor_BairroActionPerformed

    private void Botao_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botao_VoltarActionPerformed
        Menu_Principal menu = new Menu_Principal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_Botao_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Juridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Juridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Juridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Juridico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Juridico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_Entrada;
    private javax.swing.JButton Botao_Voltar;
    private javax.swing.JTextField Campo_CEP;
    private javax.swing.JTextField Campo_CNPJ;
    private javax.swing.JTextField Campo_Cidade;
    private javax.swing.JTextField Campo_DDD;
    private javax.swing.JTextField Campo_Email;
    private javax.swing.JTextField Campo_Endereco;
    private javax.swing.JTextField Campo_Estado;
    private javax.swing.JTextField Campo_Nome;
    private javax.swing.JTextField Campo_Telefone;
    private javax.swing.JTextField Campo_Tipo;
    private javax.swing.JTextField Campor_Bairro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
